const Content = [
  { 
    title: 'Status do Relacionamento',
    date: '11.01.2021',
    image: '/images/relacionamento_serio.jpg',
    img_alt: 'Relacionamento Sério',
    description: 'Em um relacionamento sério a 3!',
    video: '',
    cta: '',
  },
  { 
    title: 'Vestido Novo',
    date: '11.01.2021',
    image: '/images/aline_vestido.jpg',
    img_alt: 'Vestido Maior',
    description: 'Meu número está ficando maior! O.M.G!',
    video: '',
    cta: '',
  },
  { 
    title: 'Descansando as pernas',
    date: '11.01.2021',
    image: '/images/pernas_para_o_ar.jpg',
    img_alt: 'Pernas para o ar',
    description: 'Colocando minhas pernas para o ar',
    video: '',
    cta: '',
  },
  {
  title: 'Palpites',
  date: '11.01.2021',
  image: '/images/boy_or_girl.jpg',
  img_alt: 'Menino ou Menina?',
  description: 'Alguém arrisca? Coloca lá no grupo!',
  video: '',
  cta: '',
},
{
  title: 'Papai com seu olhar 43',
  date: '12.01.2021',
  image: '/images/papai.jpg',
  img_alt: 'Papai',
  description: 'Anota aí Juvenil, vai dar bom!',
  video: '',
  cta: '',
},
{
  title: 'Xonei',
  date: '12.01.2021',
  image: '/images/pulseira.jpg',
  img_alt: 'Pulseira',
  description: 'Bati o olho e xonei na pulseira.',
  video: '',
  cta: '',
},
{
  title: 'Bebês engraçados',
  date: '12.01.2021',
  image: '',
  img_alt: '',
  description: 'Tente não rir com esses bebês fofos.',
  video: 'https://youtu.be/MoVn6TeEW7c',
  cta: '',
},
{
  title: 'Primeiro Presente do Bebê',
  date: '18.01.2021',
  image: '/images/primeiro_presente_bebe.jpg',
  img_alt: 'Primeiro presente do bebê - macacãozinho',
  description: 'Primeiro presente do bebê dado pela Monique!',
  video: '',
  cta: '',
},
{
  title: 'Filhos são Herança do Senhor',
  date: '18.01.2021',
  image: '/images/filhos_heranca_do_senhor.jpg',
  img_alt: 'Filhos Herança do Senhor',
  description: 'Os filhos são uma benção, uma recompensa que o Senhor nos dá.',
  video: '',
  cta: '',
},
{
  title: 'Não foi dessa vez!',
  date: '28.01.2021',
  image: '/images/nao_foi_dessa_vez.jpg',
  img_alt: 'Suricato -  Não Foi Dessa Vez',
  description: 'Não foi dessa vez. Safira ou Josué estava com as pernas fechadas e não deu para saber o sexo no ultrassom.',
  video: '',
  cta: '',
},
{
  title: 'Barriga de 4 Meses',
  date: '05.02.2021',
  image: '/images/barriga_4_meses.jpg',
  img_alt: 'Barriga de 4 meses',
  description: 'Olha minha barriguinha de 4 meses!',
  video: '',
  cta: '',
},
{
  title: 'Meu coraçãozinho',
  date: '18.02.2021',
  image: '/images/meu_coracaozinho.jpeg',
  img_alt: 'Batimentos do coração do bebê',
  description: 'Olha como meu coraçãozinho bate rápido!',
  video: '',
  cta: '',
},
{
  title: 'Chá revelação do sexo do bebê',
  date: '01.03.2021',
  image: '',
  img_alt: '',
  description: 'Hoje é o grande dia!',
  video: 'https://www.youtube.com/watch?v=v8bA3fC9M7U',
  cta: '',
},
{
  title: '27 Semanas de Gestação',
  date: '18.04.2021',
  image: '/images/Safira_27_semanas_gestacao.jpeg',
  img_alt: '',
  description: 'Estamos com 27 semanas de gestação. Tá chegando!!',
  video: '',
  cta: '',
},
{
  title: '31 semanas de gestação',
  date: '16.05.2021',
  image: '/images/31_Semanas.jpeg',
  img_alt: '31 semanas de gestação',
  description: 'Mamãe, Papai, Ana Safira e Monique.',
  video: '',
  cta: '',
},
{
  title: 'Tá chegando o nosso chá de fralda',
  date: '15.05.2021',
  image: '/images/ChaFraldaSafira.jpg',
  img_alt: '31 semanas de gestação',
  description: 'Já estamos contando os dias para a chegada da nossa querida Ana Safira. Resolvemos fazer um chá de fralda, virtual por causa da pandemia infelizmente. Você pode ver a nossa listinha no botão abaixo. Clique para saber mais e aguarde mais novidade por aqui.',
  video: '',
  cta: 'https://www.listasmagalu.com/chadebebe/ana-safira-aline-e-marco',
},
{
  title: 'Venha participar do nosso chá de fralda',
  date: '09.06.2021',
  image: '/images/Berco_Ana_Safira.jpg',
  img_alt: 'Berço Ana Safira',
  description: 'Olha o berço da Ana Safira como ficou. O chá de fralda vai ser agora dia 12/06/2021 às 20h e terá sorteio de uma cesta de chocolates. Clique no botão abaixo para entrar no meet e participar do chá de fralda.',
  video: '',
  cta: 'https://meet.google.com/uou-cysh-abi',
},
{
  title: 'Chá de Fralda da Safira',
  date: '12.06.2021',
  image: '/images/ChaDeFraldaSafira.jpeg',
  img_alt: 'Chá de Fralda da Safira',
  description: 'E assim foi o nosso chá de fralda online. Quem ganhou a cesta de chocolates foi a Roberta Maia.',
  video: '',
  cta: '',
},
{
  title: 'Contagem Regressiva',
  date: '23.06.2021',
  image: '/images/10ContagemRegressiva.jpeg',
  img_alt: 'Contagem Regressiva: 10',
  description: 'Tá chegando a hora, faltam só 10 dias!',
  video: '',
  cta: '',
},
{
  title: 'Tudo pronto para o meu primeiro banhozinho!',
  date: '23.06.2021',
  image: '/images/PrimeiroBanho.jpeg',
  img_alt: 'Tudo pronto para o meu primeiro banhozinho!: 10',
  description: 'Tá tudo pronto para o meu primeiro banhozinho em casa! Cute cute!',
  video: '',
  cta: '',
},
{
  title: 'Cheguei ao mundo!',
  date: '04.07.2021',
  image: '/images/Nascimento_Ana_Safira.jpeg',
  img_alt: 'Nascimento Ana Safira',
  description: 'Cheguei no dia da independência (dos Estados Unidos porque sou chique). Estava com muita vontade de conhecer o papai e a mamãe.',
  video: '',
  cta: '',
},
{
  title: 'Passei aqui para deixar seu dia mais fofo!',
  date: '29.07.2021',
  image: '/images/Feed_Ana_Safira.jpeg',
  img_alt: 'Meu primeiro post! Rosto do bebê',
  description: 'Meu primeiro post aqui no feed, e o último também. Gostaria de agradecer ao papai, a mamãe e a você que esteve aguardando a minha chegada, muito obrigada!',
  video: '',
  cta: '',
},
]

export default Content
