const Content = [
  { 
    title: 'Status do Relacionamento',
    date: '11.01.2021',
    image: '/images/relacionamento_serio.jpg',
    img_alt: 'Relacionamento Sério',
    description: 'Em um relacionamento sério a 3!',
    video: '',
  },
  { 
    title: 'Vestido Novo',
    date: '11.01.2021',
    image: '/images/aline_vestido.jpg',
    img_alt: 'Vestido Maior',
    description: 'Meu número está ficando maior! O.M.G!',
    video: '',
  },
  { 
    title: 'Descansando as pernas',
    date: '11.01.2021',
    image: '/images/pernas_para_o_ar.jpg',
    img_alt: 'Pernas para o ar',
    description: 'Colocando minhas pernas para o ar',
    video: '',
  },
  {
  title: 'Palpites',
  date: '11.01.2021',
  image: '/images/boy_or_girl.jpg',
  img_alt: 'Menino ou Menina?',
  description: 'Alguém arrisca? Coloca lá no grupo!',
  video: '',
},
{
  title: 'Papai com seu olhar 43',
  date: '12.01.2021',
  image: '/images/papai.jpg',
  img_alt: 'Papai',
  description: 'Anota aí Juvenil, vai dar bom!',
  video: '',
},
{
  title: 'Xonei',
  date: '12.01.2021',
  image: '/images/pulseira.jpg',
  img_alt: 'Pulseira',
  description: 'Bati o olho e xonei na pulseira.',
  video: '',
},
{
  title: 'Bebês engraçados',
  date: '12.01.2021',
  image: '',
  img_alt: '',
  description: 'Tente não rir com esses bebês fofos.',
  video: 'https://youtu.be/MoVn6TeEW7c',
},
{
  title: 'Primeiro Presente do Bebê',
  date: '18.01.2021',
  image: '/images/primeiro_presente_bebe.jpg',
  img_alt: 'Primeiro presente do bebê - macacãozinho',
  description: 'Primeiro presente do bebê dado pela Monique!',
  video: '',
},
{
  title: 'Filhos são Herança do Senhor',
  date: '18.01.2021',
  image: '/images/filhos_heranca_do_senhor.jpg',
  img_alt: 'Filhos Herança do Senhor',
  description: 'Os filhos são uma benção, uma recompensa que o Senhor nos dá.',
  video: '',
},
{
  title: 'Não foi dessa vez!',
  date: '28.01.2021',
  image: '/images/nao_foi_dessa_vez.jpg',
  img_alt: 'Suricato -  Não Foi Dessa Vez',
  description: 'Não foi dessa vez. Safira ou Josué estava com as pernas fechadas e não deu para saber o sexo no ultrassom.',
  video: '',
},
{
  title: 'Barriga de 4 Meses',
  date: '05.02.2021',
  image: '/images/barriga_4_meses.jpg',
  img_alt: 'Barriga de 4 meses',
  description: 'Olha minha barriguinha de 4 meses!',
  video: '',
},
{
  title: 'Meu coraçãozinho',
  date: '18.02.2021',
  image: '/images/meu_coracaozinho.jpeg',
  img_alt: 'Batimentos do coração do bebê',
  description: 'Olha como meu coraçãozinho bate rápido!',
  video: '',
},
{
  title: 'Chá revelação do sexo do bebê',
  date: '01.03.2021',
  image: '',
  img_alt: '',
  description: 'Hoje é o grande dia!',
  video: 'https://www.youtube.com/watch?v=v8bA3fC9M7U',
},
{
  title: '27 Semanas de Gestação',
  date: '18.04.2021',
  image: '/images/Safira_27_semanas_gestacao.jpeg',
  img_alt: '',
  description: 'Estamos com 27 semanas de gestação. Tá chegando!!',
  video: '',
},
]

export default Content
